'use client';
import { useState } from 'react';
import { ArrowUpRight,Download,Share2,Trash2,BookOpen,Check,LoaderCircle } from 'lucide-react';
import Dialog from './Dialog';
import ConditionPicker from './ConditionPicker';
import type { WorkspaceRecord,RecordKind,User } from '@/lib/types';
export default function RecordDialog({record,kind,user,onClose,onSaved,onDeleted,onReview}:{record?:Partial<WorkspaceRecord>;kind:RecordKind;user:User;onClose:()=>void;onSaved:(r:WorkspaceRecord)=>void;onDeleted:(id:string)=>void;onReview:(r:WorkspaceRecord)=>void}){
  const [current,setCurrent]=useState(record);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [sharing,setSharing]=useState(false);const [publishing,setPublishing]=useState(false);const [confirmDelete,setConfirmDelete]=useState(false);const [email,setEmail]=useState('');
  const locked=!!current?.readOnly,document=kind==='document';
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);
    try{const r=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:current?.id,kind,title:f.get('title'),content:f.get('content'),diseaseId:f.get('diseaseId')??'',conditionName:f.get('conditionName')||undefined,status:f.get('status')||'In progress'})});const data=await r.json();if(!r.ok)throw new Error(data.error);onSaved(data.record);onClose();}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}
  }
  async function action(action:string,recipient?:string){setBusy(true);setError('');try{const r=await fetch('/api/records',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:current?.id,action,email:recipient})});const data=await r.json();if(!r.ok)throw new Error(data.error);setCurrent(data.record);onSaved(data.record);setNotice(action==='share'?'Read access granted.':action==='revoke'?'Access removed.':action==='publish'?'Research summary published to the community.':'Research summary is private again.');setPublishing(false);}catch(e){setError(e instanceof Error?e.message:'Update failed.');}finally{setBusy(false);}}
  return <Dialog title={current?.id?current.title||'Your item':`New ${kind}`} onClose={onClose} wide>
    {locked&&<p className="service-notice">Shared with you · read-only</p>}
    {document?<div className="document-detail"><div className="document-file-icon"><BookOpen size={36}/></div><p>{current?.fileName}</p><small>{((current?.fileSize||0)/1024).toFixed(0)} KB · Private unless you choose to share</small><div className="button-row"><a className="secondary" href={`/api/files/${current?.id}`}><Download size={16}/>Download</a><button className="primary" onClick={()=>{onReview(current as WorkspaceRecord);onClose();}}>Review with assistant<ArrowUpRight size={16}/></button></div></div>:<form className="record-form" onSubmit={save}>
      <label>{kind==='patient'?'Patient name or identifier':'Title'}<input name="title" defaultValue={current?.title||''} placeholder={kind==='patient'?'Use a name or a private reference':'What would you like to explore?'} required maxLength={160} readOnly={locked}/></label>
      <div className="form-columns"><ConditionPicker defaultValue={current?.diseaseId} disabled={locked}/><label>Status<select name="status" defaultValue={current?.status==='Published'?'In progress':current?.status||'In progress'} disabled={locked}><option>In progress</option><option>Planning</option><option>Complete</option><option>Draft</option><option>Saved</option></select></label></div>
      <label>{kind==='patient'?'Clinical notes & context':'Notes, questions & findings'}<textarea name="content" rows={7} maxLength={60000} defaultValue={current?.content||''} placeholder={kind==='patient'?'Centralize the history, observations, and questions for this patient.':'Start with a question. Add evidence, observations, and the next step.'} readOnly={locked}/></label>
      {!locked&&<button className="primary" disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:<Check size={17}/>}Save {kind}</button>}
    </form>}
    {current?.id&&!locked&&<div className="record-actions"><button onClick={()=>setSharing(!sharing)}><Share2 size={15}/>Share privately</button>{kind==='project'&&user.role==='researcher'&&<button onClick={()=>current.visibility==='public'?action('unpublish'):setPublishing(!publishing)}><BookOpen size={15}/>{current.visibility==='public'?'Unpublish':'Publish summary'}</button>}<button className="danger-link" onClick={()=>setConfirmDelete(true)}><Trash2 size={15}/>Delete</button></div>}
    {sharing&&<div className="sharing-box"><p>Give another member read access to this item. They can view its content and download an attached file.</p><div className="inline-form"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Their account email" aria-label="Recipient email"/><button className="secondary" onClick={()=>action('share',email)} disabled={busy||!email}>Share</button></div>{current?.sharedWith?.map(e=><div className="share-member" key={e}>{e}<button onClick={()=>action('revoke',e)}>Revoke</button></div>)}</div>}
    {publishing&&<div className="sharing-box"><b>Publish this saved project to the community?</b><p>Your name, saved title, and saved notes will be visible to everyone. Remove personal or patient-identifying information first. It will be labelled as community research, not peer reviewed. Attached files remain private.</p><button className="primary" disabled={busy} onClick={()=>action('publish')}>Publish saved summary</button></div>}
    {confirmDelete&&<div className="sharing-box"><p>Delete this item and any attached file? This cannot be undone.</p><div className="button-row"><button className="secondary" onClick={()=>setConfirmDelete(false)}>Keep it</button><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/records',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:current?.id})});if(!r.ok)throw new Error('Could not delete this item.');onDeleted(current!.id!);onClose();}catch(e){setError(e instanceof Error?e.message:'Delete failed.');}finally{setBusy(false);}}}>Delete item</button></div></div>}
    {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="success-notice" role="status">{notice}</p>}
  </Dialog>;
}
