'use client';
import { useEffect, useRef, useState } from 'react';
import { atlasRegions } from '@/lib/atlas-graph';
import styles from './RegionalDiscovery.module.css';

type Disease = {id:string;name:string;matched_phenotypes?:{id:string;label:string}[]};
type Group = {id:string;label:string;kind:string;member_ids:string[];region_member_ids?:string[]};
type RegionData = {region:{id:string;label:string;scope?:string};diseases:Disease[];clusters:Group[];related_regions:{id:string;label:string;pair_count:number}[];notice:string};
type Detail = {members:Disease[];cluster:Group & {pairs:{disease_a:string;disease_b:string;phenotype_similarity:{value:number|null};assessment:{status:string;unknowns:string[]};source_paths:unknown[]}[]};claims:{id:string;paper_id:string;passage:string;context:Record<string,string>;limitations:string[];locator:unknown;study_type?:string}[];papers:{id:string;identifiers:string[]}[]};
async function get<T>(query:string,signal?:AbortSignal):Promise<T>{const r=await fetch('/api/discovery?'+query,{signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Discovery unavailable');return d;}
export default function RegionalDiscovery({regionId,onRegion}:{regionId:string;onRegion:(id:string)=>void}){
 const [data,setData]=useState<RegionData>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [retry,setRetry]=useState(0);
 const [query,setQuery]=useState('');const [hits,setHits]=useState<Disease[]>([]);const [searchNotice,setSearchNotice]=useState('');const [kind,setKind]=useState('all');const [visibleCount,setVisibleCount]=useState(12);const [selected,setSelected]=useState<Disease>();const [detail,setDetail]=useState<Detail>();const [groupId,setGroupId]=useState('');const generation=useRef(0);const searchAbort=useRef<AbortController|null>(null);
 useEffect(()=>{const abort=new AbortController();setBusy(true);setError('');setData(undefined);setDetail(undefined);setGroupId('');setSelected(undefined);setVisibleCount(12);generation.current++;searchAbort.current?.abort();setHits([]);setSearchNotice('');get<RegionData>('resource=region&id='+encodeURIComponent(regionId),abort.signal).then(setData).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setBusy(false);});return()=>abort.abort();},[regionId,retry]);
 useEffect(()=>{if(!groupId)return;const abort=new AbortController();setDetail(undefined);get<Detail>('resource=cluster&id='+encodeURIComponent(groupId),abort.signal).then(setDetail).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[groupId]);
 useEffect(()=>()=>searchAbort.current?.abort(),[]);
 async function search(e:React.FormEvent){e.preventDefault();const current=++generation.current;searchAbort.current?.abort();const abort=new AbortController();searchAbort.current=abort;setSearchNotice('Searching…');try{const r=await fetch('/api/discovery?resource=search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'text',query,limit:20}),signal:abort.signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Search failed');if(current===generation.current){setHits(d.results);setSearchNotice(`${d.total} matches${d.total>20?' · showing first 20':''}${d.ambiguous_exact_match?' · choose an identifier; names are ambiguous':''}`);}}catch(e){if(!abort.signal.aborted)setSearchNotice(e instanceof Error?e.message:'Search unavailable');}}
 async function choose(hit:Disease){const current=++generation.current;setExternal([]);setVisibleCount(12);setSelected(hit);setGroupId('');setDetail(undefined);try{const response=await get<{clusters:Group[]}>('resource=clusters&entity_id='+encodeURIComponent(hit.id));if(current===generation.current)setExternal(response.clusters);}catch(e){setError(e instanceof Error?e.message:'Unavailable');}}
 const [external,setExternal]=useState<Group[]>([]);
 const groups=(selected?external:data?.clusters||[]).filter(g=>kind==='all'||g.kind===kind);
 return <aside className={styles.panel} aria-label="Body-region research">
 <h2>Connected research</h2><p>Explore recorded features, disease groups and their evidence.</p>
 <label>Body region<select aria-label="Research body region" value={regionId} onChange={e=>onRegion(e.target.value)}>{Object.entries(atlasRegions).map(([id,r])=><option key={id} value={id}>{r.label}</option>)}</select></label>
 <form onSubmit={search}><label>Search diseases, genes or pathways<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={200} required/></label><button>Search research</button></form><p role="status">{searchNotice}</p>
 {hits.map(h=><button key={h.id} className={styles.record} onClick={()=>choose(h)}>{h.name}<small>{h.id}</small></button>)}
 {busy&&<p role="status">Loading regional connections…</p>}{error&&<p role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>Retry</button></p>}
 {data&&<><h3>{data.region.label}: {data.diseases.length} diseases</h3><p>{data.region.scope||'Matched through recorded HPO features and their ontology ancestors.'}</p><p className={styles.notice}>Anatomical filters are not confirmed patient symptoms. Mappings need clinical review.</p>
 <details><summary>Inspect regional disease annotations</summary>{data.diseases.map(d=><div key={d.id}><button onClick={()=>choose(d)}>{d.name}</button><small>{d.id}</small><p>{d.matched_phenotypes?.map(h=>`${h.label} (${h.id})`).join('; ')}</p></div>)}</details>
 {selected&&<p>Groups for {selected.name} (global search; not an assertion of involvement in {data.region.label}) <button onClick={()=>{setSelected(undefined);setDetail(undefined);setGroupId('');}}>Back to region</button></p>}
 <label>Group type<select value={kind} onChange={e=>{setKind(e.target.value);setVisibleCount(12);}}><option value="all">All groups</option><option value="pathway">Shared pathway</option><option value="phenotype">Phenotype similarity</option></select></label>
 <p>{groups.length} candidate groups</p>{!groups.length&&<p>No groups in this snapshot. Missing data does not mean no connection.</p>}
 {groups.slice(0,visibleCount).map(g=><button className={styles.record} key={g.id} onClick={()=>{setGroupId(g.id);setError('');}}>{g.label}<small>{g.kind} · {g.member_ids.length} total members{g.region_member_ids?` · ${g.region_member_ids.length} in this region`:''}</small></button>)}
 {groups.length>visibleCount&&<button onClick={()=>setVisibleCount(n=>n+12)}>Show more groups</button>}
 {detail&&<section aria-label="Selected cluster evidence"><h3>{detail.cluster.label}</h3><p>Candidate group—not a validated shared mechanism.</p>{detail.members.map(m=><p key={m.id}>{m.name} <small>{m.id}</small></p>)}{detail.cluster.pairs.map(p=><details key={p.disease_a+p.disease_b}><summary>{p.disease_a} ↔ {p.disease_b}</summary><p>Phenotype similarity: {p.phenotype_similarity.value===null?'unknown':`${(p.phenotype_similarity.value*100).toFixed(1)}% exact-HPO Jaccard; not a probability`}</p><p>{p.assessment.status}</p><pre>{JSON.stringify(p,null,2)}</pre></details>)}{!detail.claims.length&&<p>No supporting paper claims supplied for these connections.</p>}{detail.claims.map(c=>{const paper=detail.papers.find(p=>p.id===c.paper_id);const pmid=paper?.identifiers.find(i=>/^PMID:\d+$/.test(i));const pmc=paper?.identifiers.find(i=>/^PMC\d+$/.test(i));return <article key={c.id}><p>Unreviewed extracted claim</p><blockquote>{c.passage}</blockquote><p>{Object.entries(c.context).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p><p>Study type: {c.study_type || 'unknown'}. Location: {JSON.stringify(c.locator)}</p><p>{c.limitations.join(' ')}</p>{pmid&&<a href={'https://pubmed.ncbi.nlm.nih.gov/'+pmid.slice(5)+'/'} target="_blank" rel="noreferrer">Open publication record</a>}{pmc&&<p><a href={'https://pmc.ncbi.nlm.nih.gov/articles/'+pmc+'/'} target="_blank" rel="noreferrer">Open full text in PMC</a></p>}</article>;})}</section>}
 <h3>Body regions connected to {data.region.label}</h3><p>Candidate disease pairs span these regions; this is not proof of organ-to-organ causation.</p>{data.related_regions.map(r=><button className={styles.record} key={r.id} onClick={()=>onRegion(r.id)}>{r.label}<small>{r.pair_count} candidate disease pairs</small></button>)}<p>{data.notice}</p></>}
 </aside>;
}
