'use client';
import { useEffect, useRef, useState } from 'react';
import { atlasRegions } from '@/lib/atlas-graph';
import styles from './RegionalDiscovery.module.css';

type Disease = {id:string;name:string;matched_phenotypes?:{id:string;label:string}[]};
type Group = {id:string;label:string;kind:string;member_ids:string[];region_member_ids?:string[];shared_process_ids?:string[]};
type Coverage = {diseases:number;clustered_diseases:number;phenotype_profiles:number;publications:number;publications_with_claims:number;claims:number;reviewed_claims:number;evidence_files:number;truncated_source_responses:number;excluded_or_unresolved_items:number};
type Neighbors = {annotation_status:string;notice:string;total:number;candidates:(Disease & {score:number;exact_hpo_jaccard:number;shared_features:{id:string;label:string;exact_in_both:boolean}[]})[]};
type RegionData = {coverage:Coverage;region:{id:string;label:string;scope?:string};diseases:Disease[];clusters:Group[];related_regions:{id:string;label:string;pair_count:number}[];notice:string};
type Detail = {members:Disease[];cluster:Group & {pairs:{disease_a:string;disease_b:string;phenotype_similarity:{value:number|null};assessment:{status:string;unknowns:string[];supporting_claim_ids?:string[];contradicting_claim_ids?:string[]};source_paths:unknown[]}[]};claims:{id:string;paper_id:string;passage:string;context:Record<string,string>;limitations:string[];locator:unknown;study_type?:string}[];papers:{id:string;identifiers:string[]}[]};
type CommunityRecord = {id:string;kind:string;name:string;description:string;disease_ids:string[];process_ids:string[];match_reasons:{field:string;id:string}[];community_ids?:string[];owner?:string;goal?:string;access_conditions?:string;reuse_checks?:string[];next_step?:string;status?:string;evidence:{claim_id:string;publication_id:string;url:string;review_status:string}[]};
type CommunitySection = {kind:string;label:string;items:CommunityRecord[];count:number};
type Communities = {sections:CommunitySection[];notice:string};
async function get<T>(query:string,signal?:AbortSignal):Promise<T>{const r=await fetch('/api/discovery?'+query,{signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Discovery unavailable');return d;}
export default function RegionalDiscovery({regionId,onRegion}:{regionId:string;onRegion:(id:string)=>void}){
 const [data,setData]=useState<RegionData>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [retry,setRetry]=useState(0);
 const [query,setQuery]=useState('');const [hits,setHits]=useState<Disease[]>([]);const [searchNotice,setSearchNotice]=useState('');const [kind,setKind]=useState('all');const [visibleCount,setVisibleCount]=useState(12);const [selected,setSelected]=useState<Disease>();const [detail,setDetail]=useState<Detail>();const [groupId,setGroupId]=useState('');const generation=useRef(0);const searchAbort=useRef<AbortController|null>(null);
 useEffect(()=>{const abort=new AbortController();setBusy(true);setError('');setData(undefined);setDetail(undefined);setGroupId('');setSelected(undefined);setVisibleCount(12);generation.current++;searchAbort.current?.abort();setHits([]);setSearchNotice('');get<RegionData>('resource=region&id='+encodeURIComponent(regionId),abort.signal).then(setData).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setBusy(false);});return()=>abort.abort();},[regionId,retry]);
 useEffect(()=>{if(!groupId)return;const abort=new AbortController();setDetail(undefined);get<Detail>('resource=cluster&id='+encodeURIComponent(groupId),abort.signal).then(setDetail).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[groupId]);
 useEffect(()=>()=>searchAbort.current?.abort(),[]);
 async function search(e:React.FormEvent){e.preventDefault();const current=++generation.current;searchAbort.current?.abort();const abort=new AbortController();searchAbort.current=abort;setSearchNotice('Searching…');try{const r=await fetch('/api/discovery?resource=search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'text',query,limit:20}),signal:abort.signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Search failed');if(current===generation.current){setHits(d.results);setSearchNotice(`${d.total} matches${d.total>20?' · showing first 20':''}${d.ambiguous_exact_match?' · choose an identifier; names are ambiguous':''}`);}}catch(e){if(!abort.signal.aborted)setSearchNotice(e instanceof Error?e.message:'Search unavailable');}}
 async function choose(hit:Disease){
  const current=++generation.current;setExternal([]);setVisibleCount(12);setSelected(hit);setGroupId('');setDetail(undefined);setCommunities(undefined);setCommunityError('');setNeighbors(undefined);setNeighborError('');setNeighborsBusy(true);
  const results=await Promise.allSettled([
   get<{clusters:Group[]}>('resource=clusters&entity_id='+encodeURIComponent(hit.id)),
   get<Neighbors>('resource=neighbors&entity_id='+encodeURIComponent(hit.id)),
   get<Communities>('resource=communities&disease_id='+encodeURIComponent(hit.id))
  ]);
  if(current!==generation.current)return;
  if(results[0].status==='fulfilled')setExternal(results[0].value.clusters);else setError('Cluster lookup unavailable; this is not evidence of no connections.');
  if(results[1].status==='fulfilled')setNeighbors(results[1].value);else setNeighborError('Phenotype candidate lookup unavailable.');
  if(results[2].status==='fulfilled')setCommunities(results[2].value);else setCommunityError('Community catalog unavailable.');
  setNeighborsBusy(false);
 }

 const [neighbors,setNeighbors]=useState<Neighbors>();const [neighborError,setNeighborError]=useState('');const [neighborsBusy,setNeighborsBusy]=useState(false);
 const [external,setExternal]=useState<Group[]>([]);
 const [communities,setCommunities]=useState<Communities>();const [communityError,setCommunityError]=useState('');
 const groups=(selected?external:data?.clusters||[]).filter(g=>kind==='all'||g.kind===kind);
 useEffect(()=>{if(!detail)return;const processes=[...new Set(detail.cluster.shared_process_ids||[])];if(!processes.length)return;const abort=new AbortController();setCommunities(undefined);setCommunityError('');Promise.allSettled(processes.slice(0,8).map(process=>get<Communities>('resource=communities&process_id='+encodeURIComponent(process),abort.signal))).then(results=>{if(abort.signal.aborted)return;const sections=new Map<string,CommunitySection>();let notice='';for(const result of results){if(result.status!=='fulfilled')continue;notice=result.value.notice||notice;for(const section of result.value.sections){const saved=sections.get(section.kind)||{...section,items:[],count:0};const existing=new Set(saved.items.map(item=>item.id));for(const item of section.items)if(!existing.has(item.id)){saved.items.push(item);existing.add(item.id);}saved.count=saved.items.length;sections.set(section.kind,saved);}}setCommunities({sections:[...sections.values()],notice});if(!sections.size)setCommunityError('No matching community records for these shared processes yet.');});return()=>abort.abort();},[detail]);
 return <aside className={styles.panel} aria-label="Body-region research">
 <h2>Connected research</h2><p>Explore recorded features, disease groups and their evidence.</p>
 <label>Body region<select aria-label="Research body region" value={regionId} onChange={e=>onRegion(e.target.value)}>{Object.entries(atlasRegions).map(([id,r])=><option key={id} value={id}>{r.label}</option>)}</select></label>
 <form onSubmit={search}><label>Search diseases, genes or pathways<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={200} required/></label><button>Search research</button></form><p role="status">{searchNotice}</p>
 {hits.map(h=><button key={h.id} className={styles.record} onClick={()=>choose(h)}>{h.name}<small>{h.id}</small></button>)}
 {busy&&<p role="status">Loading regional connections…</p>}{error&&<p role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>Retry</button></p>}
 {data&&<><details><summary>Repository coverage (saved snapshot)</summary><p>{data.coverage.diseases} diseases · {data.coverage.phenotype_profiles} with phenotype profiles · {data.coverage.clustered_diseases} with candidate groups · {data.coverage.publications} saved publications ({data.coverage.publications_with_claims} with extracted claims) · {data.coverage.claims} extracted claims · {data.coverage.reviewed_claims} reviewed claims.</p><p>{data.coverage.evidence_files} imported evidence files · {data.coverage.truncated_source_responses} truncated source responses · {data.coverage.excluded_or_unresolved_items} excluded/unresolved items. These totals exclude live search results and raw files that have not been imported. The graph counters describe loaded records, not repository totals.</p></details><h3>{data.region.label}: {data.diseases.length} diseases</h3><p>{data.region.scope||'Matched through recorded HPO features and their ontology ancestors.'}</p><p className={styles.notice}>Anatomical filters are not confirmed patient symptoms. Mappings need clinical review.</p>
 <details><summary>Inspect regional disease annotations</summary>{data.diseases.map(d=><div key={d.id}><button onClick={()=>choose(d)}>{d.name}</button><small>{d.id}</small><p>{d.matched_phenotypes?.map(h=>`${h.label} (${h.id})`).join('; ')}</p></div>)}</details>
 {selected&&<p>Groups for {selected.name} (global search; not an assertion of involvement in {data.region.label}) <button onClick={()=>{setSelected(undefined);setDetail(undefined);setGroupId('');}}>Back to region</button></p>}
 {selected&&<CommunityMatches communities={communities} error={communityError} title={`Communities connected to ${selected.name}`}/>}
 {selected&&<section aria-label="Exploratory phenotype candidates"><h3>Related phenotype candidates for {selected.name}</h3>{neighborsBusy&&<p role="status">Comparing recorded HPO features and their ancestors…</p>}{neighborError&&<p role="alert">{neighborError} <button onClick={()=>choose(selected)}>Retry candidates</button></p>}{neighbors&&<><p>{neighbors.notice}</p>{neighbors.annotation_status!=='loaded'?<p>No phenotype profile loaded for this record. Similarity is unknown.</p>:<p>{neighbors.total} candidates with informative overlap; showing up to 10. This is a ranking, not a new cluster.</p>}{neighbors.candidates.map(c=><div key={c.id}><button onClick={()=>choose(c)}>{c.name}</button><p>{(c.score*100).toFixed(1)}% ontology-weighted overlap · {(c.exact_hpo_jaccard*100).toFixed(1)}% exact-term overlap. Neither is a probability.</p><p>{c.shared_features.map(f=>`${f.label} (${f.id}; ${f.exact_in_both?'exact in both':'shared ancestor'})`).join('; ')}</p></div>)}</>}</section>}
 <label>Group type<select value={kind} onChange={e=>{setKind(e.target.value);setVisibleCount(12);}}><option value="all">All groups</option><option value="pathway">Shared pathway</option><option value="phenotype">Phenotype similarity</option></select></label>
 <p>{groups.length} candidate groups</p>{!groups.length&&<p>No groups in this snapshot. Missing data does not mean no connection.</p>}
 {groups.slice(0,visibleCount).map(g=><button className={styles.record} key={g.id} onClick={()=>{setGroupId(g.id);setError('');}}>{g.label}<small>{g.kind} · {g.member_ids.length} total members{g.region_member_ids?` · ${g.region_member_ids.length} in this region`:''}</small></button>)}
 {groups.length>visibleCount&&<button onClick={()=>setVisibleCount(n=>n+12)}>Show more groups</button>}
 {detail&&<section aria-label="Selected cluster evidence"><h3>{detail.cluster.label}</h3><p>Candidate group—not a validated shared mechanism.</p><CommunityMatches communities={communities} error={communityError} title="Communities connected to this group"/>{detail.members.map(m=><p key={m.id}>{m.name} <small>{m.id}</small></p>)}{detail.cluster.pairs.map(p=><details key={p.disease_a+p.disease_b}><summary>{p.disease_a} ↔ {p.disease_b}</summary><p>Phenotype similarity: {p.phenotype_similarity.value===null?'unknown':`${(p.phenotype_similarity.value*100).toFixed(1)}% exact-HPO Jaccard; not a probability`}</p><p>{p.assessment.status} · {p.assessment.supporting_claim_ids?.length||0} supporting claim references · {p.assessment.contradicting_claim_ids?.length||0} potential contradiction references. These do not constitute scientific review.</p>{p.assessment.unknowns?.map((u,i)=><p key={i}>{u}</p>)}<pre>{JSON.stringify(p,null,2)}</pre></details>)}{!detail.claims.length&&<p>No supporting paper claims supplied for these connections.</p>}{detail.claims.map(c=>{const paper=detail.papers.find(p=>p.id===c.paper_id);const pmid=paper?.identifiers.find(i=>/^PMID:\d+$/.test(i));const pmc=paper?.identifiers.find(i=>/^PMC\d+$/.test(i));return <article key={c.id}><p>Unreviewed extracted claim</p><blockquote>{c.passage}</blockquote><p>{Object.entries(c.context).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p><p>Study type: {c.study_type || 'unknown'}. Location: {JSON.stringify(c.locator)}</p><p>{c.limitations.join(' ')}</p>{pmid&&<a href={'https://pubmed.ncbi.nlm.nih.gov/'+pmid.slice(5)+'/'} target="_blank" rel="noreferrer">Open publication record</a>}{pmc&&<p><a href={'https://pmc.ncbi.nlm.nih.gov/articles/'+pmc+'/'} target="_blank" rel="noreferrer">Open full text in PMC</a></p>}</article>;})}</section>}
 <h3>Body regions connected to {data.region.label}</h3><p>Candidate disease pairs span these regions; this is not proof of organ-to-organ causation.</p>{data.related_regions.map(r=><button className={styles.record} key={r.id} onClick={()=>onRegion(r.id)}>{r.label}<small>{r.pair_count} candidate disease pairs</small></button>)}<p>{data.notice}</p></>}
 </aside>;
}

function CommunityMatches({communities,error,title}:{communities?:Communities;error:string;title:string}){
 const items=(communities?.sections||[]).flatMap(section=>section.items.map(item=>({...item,section:section.label})));
 if(error)return <section className={styles.communities}><h3>{title}</h3><p>{error}</p></section>;
 if(!items.length)return null;
 return <section className={styles.communities} aria-label={title}><h3>{title}</h3><p>{communities?.notice}</p>{items.map(item=><article key={item.id} className={styles.communityCard}><small>{item.section} · {item.kind}</small><h4>{item.name}</h4><p>{item.description}</p>{item.goal&&<p>Goal: {item.goal}</p>}{item.reuse_checks?.length? <p>Reuse checks: {item.reuse_checks.join('; ')}</p>:null}{item.next_step&&<p>Next step: {item.next_step}</p>}{item.evidence?.map(link=><a key={link.claim_id+link.publication_id} href={link.url} target="_blank" rel="noreferrer">{link.publication_id} · {link.review_status}</a>)}</article>)}</section>;
}
